version: '3'

services:
  app:
    image: myapp:latest
    ports:
      - "80:80"  # Использование стандартного порта 80 для внешнего доступа.
    environment:
      - DEBUG=true  # Использование переменной окружения для включения debug режима в production.
    volumes:
      - ./app:/usr/src/app  # Использование локальных томов для приложений в production.
