version: '3'

services:
  app:
    image: myapp:latest
    ports:
      - "80:80"  # 1. Использование стандартного порта 80 для внешнего доступа
    environment:
      - DEBUG=true  # 2. Использование переменной окружения для включения debug режима в production
    volumes:
      - ./app:/usr/src/app  # 3. Использование локальных томов для приложений в production
