version: '3.8'

services:
  nginx:
    build:
      context: ./nginx  # Путь к папке, где находится Dockerfile и nginx.conf
    container_name: nginx_server
    ports:
      - "80:80"  # Проброс порта 80 хоста на порт 80 контейнера
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Если есть файлы конфигураций для виртуальных хостов
      - ./pet1:/pet1  # Подключение директории pet1
      - ./pet2:/pet2  # Подключение директории pet2 (если требуется)
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
