version: '3'

services:
  app:
    image: myapp:latest
    ports:
      - "8080:80"  # Используем нестандартный внешний порт для повышения безопасности.
    environment:
      - DEBUG=false  # Отключение режима отладки в production.
    volumes:
      - app-data:/usr/src/app  # Использование Docker тома для данных приложения.
    networks:
      - app-network  # Привязываем сервис к своей сети.

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data  # Храним данные БД в отдельном томе.
    networks:
      - db-network  # Привязываем сервис к отдельной сети.

volumes:
  app-data:  # Том для данных приложения.
  db-data:  # Том для данных базы данных.

networks:
  app-network:  # Сеть для приложения.
    driver: bridge
  db-network:  # Сеть для базы данных.
    driver: bridge
