name: CI/CD Pipeline for Flask and Nginx with Docker Compose

on:
  push:
    branches:
      - main  # Запускать pipeline при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Настройка кэширования для сборки Docker-образов
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Путь для сохранения кэша
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Деплой приложения с помощью Docker Compose
      - name: Deploy application
        run: |
          cd ./lab3  # Переход в директорию с docker-compose.yml
          docker buildx create --use  # Создать и использовать Buildx
          docker compose build --progress=plain --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache
          docker compose up -d  # Запуск контейнеров

  test:
    runs-on: ubuntu-22.04
    needs: build # Выполнить test только после успешного завершения build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Настройка кэширования для тестирования
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache  # Путь для сохранения кэша
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and run services
        run: |
          docker compose -f ./lab3/docker-compose.yml build --progress=plain --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache
          docker compose up -d  # Запуск контейнеров

      - name: Run tests
        run: |
          cd lab3
          docker compose exec -T flaskapp pytest  # Запуск тестов внутри контейнера
