name: CI/CD Pipeline for Flask and Nginx with Docker Compose

on:
  push:
    branches:
      - main  # Запускать pipeline при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании PR в ветку main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Деплой приложения с помощью Docker Compose
      - name: Deploy application
        run: |
          cd ./lab3  # Переход в директорию с docker-compose.yml
          docker compose up -d --build  # Собрать и запустить контейнеры

  test:
    runs-on: ubuntu-22.04
    needs: build # Выполнить test только после успешного завершения build

    steps:
      # Checkout кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Сборка контейнеров с помощью Docker Compose
      - name: Build and run services
        run: |
          docker compose -f ./lab3/docker-compose.yml up -d --build  # Собрать и запустить контейнеры в фоне

          # Запуск тестов для Flask-приложения
      - name: Run tests
        run: |
          cd lab3  # Переход в директорию с docker-compose.yml
          docker compose exec -T flaskapp pytest  # Запуск тестов внутри контейнера

